import { supabase } from "./supabase";
import type { User } from "./supabase";

export type CRMUser = User;

export const createUserInDb = async (userData: Partial<CRMUser>) => {
  // Note: ID should be provided or auto-generated by the database
  const { data, error } = await supabase
    .from("users")
    .insert([userData] as any);
  if (error) throw error;
  return data;
};

export const updateUserInDb = async (id: string, updates: Partial<CRMUser>) => {
  const { data, error } = await supabase
    .from("users")
    .update(updates as any as never)
    .eq("id", id);
  if (error) throw error;
  return data;
};

export const getAllUsersInDb = (callback: (users: CRMUser[]) => void) => {
  // Initial fetch
  const fetchUsers = async () => {
    const { data, error } = await supabase
      .from("users")
      .select("*")
      .order("name", { ascending: true });
    
    if (error) {
      console.error("Error fetching users:", error);
      return;
    }
    
    if (data) callback(data);
  };

  fetchUsers();

  // Realtime subscription
  const channel = supabase
    .channel('users-list-changes')
    .on(
      'postgres_changes',
      {
        event: '*',
        schema: 'public',
        table: 'users',
      },
      () => {
        fetchUsers();
      }
    )
    .subscribe();

  // Return unsubscribe function matching Firebase's onSnapshot signature
  return () => {
    supabase.removeChannel(channel);
  };
};

export const deleteUserInDb = async (id: string) => {
  const { error } = await supabase
    .from("users")
    .delete()
    .eq("id", id);
  if (error) throw error;
};
